### What is pandas?
- pandas is a python library for data analysis and data manipulation.
- Pandas is a Python library used for data manipulation and analysis, especially with structured data like tables (DataFrames).

### Why we use pandas?
- We use Pandas because it makes working with structured data (like tables, CSVs, Excel files) fast and easy—allowing you to clean, analyze, and manipulate data with very simple code instead of complex logic.

### Types of Pandas!
- Series → 1D labeled array (like a single column)
- DataFrame → 2D labeled data structure (like a table with rows & columns)

In [68]:
# import pandas
import pandas as pd
import numpy as np

### series from list

In [69]:
# string
country = ['india','pakistan','shri lanka', 'thailand']
pd.Series(country)

0         india
1      pakistan
2    shri lanka
3      thailand
dtype: object

In [70]:
# integers
runs = [10,20,30,40,50]
pd.Series(runs)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [71]:
# custom index
index = [1,2,3,4,5,6,7,8,9]
country = ['india','pakistan','shri lanka', 'thailand', 'myanamar', 'china', 'afghanistan', 'bangladesh', 'nepal']
c = pd.Series(country, index=index, name='tondo') # setting a name
c

# we can do this thing using dictionary as well.

1          india
2       pakistan
3     shri lanka
4       thailand
5       myanamar
6          china
7    afghanistan
8     bangladesh
9          nepal
Name: tondo, dtype: object

### Series Attributes

In [72]:
# size
c.size

9

In [73]:
# dtype
c.dtype

dtype('O')

In [74]:
# name
c.name

'tondo'

In [75]:
# is_unique
c.is_unique

True

In [76]:
# index
c.index

Index([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [77]:
# values
# return numpy array
c.values

array(['india', 'pakistan', 'shri lanka', 'thailand', 'myanamar', 'china',
       'afghanistan', 'bangladesh', 'nepal'], dtype=object)

### Series using read_csv

In [78]:
# with one column
bollywood_csv = pd.read_csv('../datasets/bollywood.csv') # this squeeze works if your csv have one coloumn, in new pandas this one is deprecated.
bollywood_csv

,actorId,actorName,movieCount,ratingSum,normalizedMovieRank,googleHits,normalizedGoogleRank,normalizedRating
0,373,Aamir Khan,11,1170,9.44862,2460000,7.34283,10.00000
1,374,Shah Rukh Khan,23,2000,7.55009,2670000,7.88458,9.22674
2,375,Salman Khan,36,2340,5.40217,3490000,10.00000,9.20821
3,376,Katrina Kaif,17,1640,8.48082,2120000,6.46570,8.94852
4,377,Deepika Padukone,16,1080,5.64674,3000000,8.73591,8.62716
...,...,...,...,...,...,...,...,...
296,669,Achint Kaur,4,80,1.00000,0,NaN,1.00000
297,670,Yuvika Chaudhry,5,100,1.00000,0,NaN,1.00000
298,671,Pankaj Berry,5,100,1.00000,0,NaN,1.00000
299,672,Varun Dhawan,0,0,NaN,0,NaN,4.74000
300,673,Nargis Fakhri,0,0,NaN,0,NaN,4.80000

### Series Method

In [79]:
# head
bollywood_csv.head()

,actorId,actorName,movieCount,ratingSum,normalizedMovieRank,googleHits,normalizedGoogleRank,normalizedRating
0,373,Aamir Khan,11,1170,9.44862,2460000,7.34283,10.00000
1,374,Shah Rukh Khan,23,2000,7.55009,2670000,7.88458,9.22674
2,375,Salman Khan,36,2340,5.40217,3490000,10.00000,9.20821
3,376,Katrina Kaif,17,1640,8.48082,2120000,6.46570,8.94852
4,377,Deepika Padukone,16,1080,5.64674,3000000,8.73591,8.62716

In [80]:
# tail
bollywood_csv.tail()

,actorId,actorName,movieCount,ratingSum,normalizedMovieRank,googleHits,normalizedGoogleRank,normalizedRating
296,669,Achint Kaur,4,80,1.0,0,NaN,1.00
297,670,Yuvika Chaudhry,5,100,1.0,0,NaN,1.00
298,671,Pankaj Berry,5,100,1.0,0,NaN,1.00
299,672,Varun Dhawan,0,0,NaN,0,NaN,4.74
300,673,Nargis Fakhri,0,0,NaN,0,NaN,4.80

In [81]:
# sample
bollywood_csv.sample(5)

,actorId,actorName,movieCount,ratingSum,normalizedMovieRank,googleHits,normalizedGoogleRank,normalizedRating
206,579,Seema Biswas,11,280,1.53360,56100,1.14129,1.95457
296,669,Achint Kaur,4,80,1.00000,0,NaN,1.00000
193,566,Dino Morea,14,340,1.41925,198000,1.50737,2.09804
39,412,Preity Zinta,16,880,4.42391,877000,3.25904,4.80881
52,425,Om Puri,32,1100,2.40625,1230000,4.16970,4.17789

In [88]:
# value count -> movies
movies = pd.read_csv('../datasets/disney_movies.csv')
movies.value_counts()

movie_title                   release_date  genre      mpaa_rating  total_gross  inflation_adjusted_gross
101 Dalmatians                1961-01-25    Comedy     G            153000000    1362870985                  1
Mulan                         1998-06-19    Adventure  G            120620254    216807832                   1
Step Up 2 the Streets         2008-02-14    Drama      PG-13        58017783     68118371                    1
Step Up                       2006-08-11    Drama      PG-13        65328121     84078780                    1
Stella                        1990-02-02    Drama      PG-13        20062347     40077147                    1
                                                                                                            ..
Gone in 60 Seconds            2000-06-09    Action     PG-13        101643008    158970411                   1
Gone Fishin'                  1997-05-30    Comedy     PG           19745922     36265379                    1
Goal! The Dream Begins        2006-05-12    Drama      PG           4283255      5512647                     1
Goal! 2: Living the Dream...  2008-08-29    Drama      PG-13        225067       264247                      1
crazy/beautiful               2001-06-29    Drama      PG-13        16929123     25214223                    1
Name: count, Length: 513, dtype: int64